swagger: '2.0'
info:
    description: This is the swagger file that goes with our server code
    version: '1.0.0'
    title: Swagger Rest Article
consumes:
    - application/json
produces:
    - application/json

basePath: /api

paths:
    /user:
        get:
            operationId: user.get_all
            tags:
                - user
            summary: Read the entire list of user
            description: Read the list of user
            responses:
                200:
                    description: Successfully read user list data
                    schema:
                        type: array
                        items:
                            properties:
                                full_name:
                                    type: string
                                email:
                                    type: string
                                age:
                                    type: integer
                                user_id:
                                    type: string

        post:
            operationId: user.post
            tags:
                - user
            summary: Create a user and add it to the user list
            description: Create a new user in the user list
            parameters:
                - name: user
                  in: body
                  description: user to create
                  required: True
                  schema:
                      type: object
                      properties:
                          full_name:
                              type: string
                              description: Full name of user to create
                          email:
                              type: string
                              description: Email user to create
                          age:
                              type: integer
                              description: Age of user to create
            responses:
                201:
                    description: Successfully created user in list

    /user/{user_id}:
        get:
            operationId: user.get_by_id
            tags:
                - user
            summary: Read one user from the user list
            description: Read one user from the user list
            parameters:
                - name: user_id
                  in: path
                  description: user_id of the user to get from data
                  type: string
                  required: True
            responses:
                200:
                    description: Successfully read user from user data
                    schema:
                        properties:
                            full_name:
                                type: string
                            email:
                                type: string
                            age:
                                type: integer
                            user_id:
                                type: string

        put:
            operationId: user.put
            tags:
                - user
            summary: Update a user in the user list
            description: Update a user in the user list
            parameters:
                - name: user_id
                  in: path
                  description: user_id of the user to update data
                  type: string
                  required: True
                - name: user
                  in: body
                  schema:
                      type: object
                      properties:
                          full_name:
                              type: string
                          email:
                              type: string
                          age:
                              type: integer
                          user_id:
                              type: string
            responses:
                200:
                    description: Successfully updated user in user list

        delete:
            operationId: user.delete
            tags:
                - user
            summary: Delete a user from the user list
            description: Delete a user
            parameters:
                - name: user_id
                  in: path
                  type: string
                  required: True
            responses:
                200:
                    description: Successfully deleted a user from user list
